###############################################
# rove_servo_parameters.yaml
# Full parameter set for MoveIt Servo on the Rove arm
###############################################

# Whether the robot is started in a Gazebo simulation environment
use_gazebo: false  # Change to true if you launch Gazebo

## Properties of incoming commands
command_in_type: "speed_units"  # "unitless" or "speed_units"
scale:
  # Scale parameters for speed_units
  linear: 0.2       # Max linear velocity in [m/s] for Cartesian commands
  rotational: 0.5   # Max angular velocity in [rad/s] for Cartesian commands

# Optionally override Servo's internal velocity scaling when near singularity or collision
# override_velocity_scaling_factor: 0.0  # valid range [0.0:1.0]

## Properties of outgoing commands
publish_period: 0.033      # Publish rate in seconds
low_latency_mode: false    # Publish as soon as command received (publish_period ignored if true)

# What type of topic does your robot driver expect?
command_out_type: "trajectory_msgs/JointTrajectory"

# What to publish? (band-width saving options)
publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

## Plugins for smoothing outgoing commands
# smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"

# Is this node the primary PlanningScene monitor?
is_primary_planning_scene_monitor: true

## MoveIt properties
move_group_name: "Arm"        # Must match the group name in your SRDF
planning_frame: "RoveCore"    # Root link of the Rove URDF (replaces panda_link0)

## Other frames
# End-effector and command frames
ee_frame_name: "ArmSectionE"     # Tip link that exists in the URDF
robot_link_command_frame: "RoveCore"  # Frame commands are expressed in

## Stopping behaviour
incoming_command_timeout: 0.1                  # Stop servoing if no new cmd after X s
num_outgoing_halt_msgs_to_publish: 4           # Number of halt messages to publish

## Handling of singularities and joint limits
singularity_distance_threshold: 0.05           # Start decelerating near singularity
# lower_singularity_threshold: 50.0
# hard_stop_singularity_threshold: 75.0
# joint_limit_margin: 0.1
# leaving_singularity_threshold_multiplier: 2.0

## Topic names
cartesian_command_in_topic: "/servo_node/cartesian_cmds"  # Cartesian twist commands
# joint_command_in_topic: ""  # Joint command topic (add if needed)
# joint_topic: ""             # Joint states topic (override if needed)
# status_topic: ""            # Status topic (add if needed)
# command_out_topic: ""       # Outgoing commands topic (add if needed)

## Collision checking for the entire robot body
check_collisions: true
collision_check_rate: 10.0                      # [Hz]
self_collision_proximity_threshold: 0.001       # [m]
scene_collision_proximity_threshold: 0.1        # [m]

## Low-pass filter coefficients
low_pass_filter_coeff:
  linear: 0.1
  rotational: 0.1
